name: Checks

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [tests, lint, typecheck]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.10"

      - name: Install The Project
        run: uv sync --locked --all-extras --dev

      - name: Run Task
        run: |
          if [ "${{ matrix.task }}" = "tests" ]; then
            uv run pytest tests/ -vv
          elif [ "${{ matrix.task }}" = "lint" ]; then
            uv run ruff check
          else
            uv run ty check
          fi
